### ISSUE TITLE
Cannot reach status.ampproject.org

### ISSUE THREAD

**Issue by sisidovski** [ampproject/amp-status#2] opened 2018-12-27 07:38 UTC
Hi

Is status page still maintained? https://status.ampproject.org/
I was reading AMP documentation and noticed the link of status page in header is broken.
Can someone check the certificate?

```
$ curl -v https://status.ampproject.org/
*   Trying 2606:4700::6812:fe8...
* TCP_NODELAY set
* Connected to status.ampproject.org (2606:4700::6812:fe8) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS alert, Server hello (2):
* error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by prateekbh** [comment] 2018-12-27 13:30
@erwinmombay

**Comment by danielrozenberg** [comment] 2019-01-03 16:52
Thanks for reporting this @sisidovski! The SSL certificate failed to auto-renew at beginning of December, I'm taking steps to resolve this ASAP

**Comment by rudygalfi** [comment] 2019-01-07 20:28
I think this is still unresolved. Is there any update?

**Comment by jpettitt** [comment] 2019-01-07 20:50
It looks like there is an `http` server listening on the `https` port which is why the `Server hello` is failing.

 `````
jpettitt@shmoo:~/scratch$ telnet status.ampproject.org 443
Trying 2606:4700::6812:fe8...
Connected to status.ampproject.org.cdn.cloudflare.net.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.1 400 Bad Request
Server: cloudflare
Date: Mon, 07 Jan 2019 20:46:03 GMT
Content-Type: text/html
Content-Length: 269
Connection: close
CF-RAY: -

<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>cloudflare</center>
</body>
</html>
Connection closed by foreign host.
jpettitt@shmoo:~/scratch$ wget https://status.ampproject.org:443/
--2019-01-07 12:46:27--  https://status.ampproject.org/
Resolving status.ampproject.org (status.ampproject.org)... 2606:4700::6812:ee8, 2606:4700::6812:fe8, 104.18.15.232, ...
Connecting to status.ampproject.org (status.ampproject.org)|2606:4700::6812:ee8|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [40]: Handshake failed
Unable to establish SSL connection.
jpettitt@shmoo:~/scratch$ 
````

**Comment by danielrozenberg** [comment] 2019-01-07 21:34
@jpettitt you are correct, but the root cause of it is a subtle issue of bureaucracy and SSL cert trust :)

@sisidovski yes, I hope to resolve this within a week. Essentially what happened is that `ampproject.org` is a domain owned by Google, but `status.ampproject.org` specifically is served via CloudFlare's CDN (and hosted as a GitHub Page) - last year CloudFlare graciously offered to serve this page for us, so that the page will benefit from their CDN and from being served behind SSL (which GitHub Pages doesn't support for custom domains, only for pages hosted directly on `github.io`) with an auto-renewing certificate.

However, Google added a [CAA](https://en.wikipedia.org/wiki/DNS_Certification_Authority_Authorization) was added to `ampproject.org` in July, which in turn prevented CloudFlare from renewing the SSL certificate when it expired in December.

I'm currently in the process of getting Google to add DigiCert (CloudFlare's SSL provider of choice) as an alternate CAA for `status.ampproject.org`. This is a bureaucratic step that unfortunately takes some time, but will probably be resolved in a few days.

Hope this helps shed some light on the situation!

**Comment by sisidovski** [comment] 2019-01-08 05:47
@danielrozenberg I see. I totally understood the current situation, that's a little bit complicated. Thank you for your explanation!

**Comment by danielrozenberg** [comment] 2019-01-11 19:27
https://status.ampproject.org/ is accessible once more. Again, thanks for letting us know!

**Closed as completed by danielrozenberg** 2019-01-11 19:27 UTC
